/*
 * 運命リズム診断 — 今日の一歩プール（各宮8本）
 * 選び方: 日の宮×THEMEのmotion一致→日付で回転
 * 2026-08-25 せいこさんの声基準（day_base 27本）に合わせてCodex再生成・クレア検品済み。
 * status:'draft'＝せいこさんの週次チェック前。承認されたら status を外す。
 */
'use strict';
(function (root, factory) {
  if (typeof module === 'object' && module.exports) { module.exports = factory(); }
  else { root.UR_ACTIONS = factory(); }
})(typeof self !== 'undefined' ? self : this, function () {
  return [
    {"id":"ac-1-01","palace":1,"text":"気になっていることを、思いつくまま3つメモ。","motion":["reflect"],"life_theme":["決断"],"status":"draft"},
    {"id":"ac-1-02","palace":1,"text":"来月やりたいことを、手帳の余白にひとつ書こう。","motion":["reflect"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-1-03","palace":1,"text":"保存したままの記事をひとつ、朝のうちに読む。","motion":["reflect"],"life_theme":["学び"],"status":"draft"},
    {"id":"ac-1-04","palace":1,"text":"「私、ほんとうは何がしたい？」と一度だけ考える。","motion":["reflect"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-1-05","palace":1,"text":"仕事で試したいアイデアに、仮の名前をつけておく。","motion":["reflect"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-1-06","palace":1,"text":"ふと浮かんだ言葉を、30秒だけ音声メモに残して。","motion":["reflect"],"life_theme":["発信"],"status":"draft"},
    {"id":"ac-1-07","palace":1,"text":"楽しみな予定をひとつ、カレンダーに先に入れよう。","motion":["reflect"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-1-08","palace":1,"text":"いつか欲しいものをひとつ調べて、画像を保存。","motion":["reflect"],"life_theme":["お金"],"status":"draft"},
    {"id":"ac-2-01","palace":2,"text":"机の上から、もう使わない紙を3枚だけ片づける。","motion":["prepare"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-2-02","palace":2,"text":"バッグの中を見て、明日いらないものをひとつ出す。","motion":["prepare"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-2-03","palace":2,"text":"首と肩をゆっくり回して、呼吸を3回。","motion":["prepare"],"life_theme":["身体"],"status":"draft"},
    {"id":"ac-2-04","palace":2,"text":"後回しにしていた返信を、ひとつだけ返しておこう。","motion":["prepare"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-2-05","palace":2,"text":"今日やらないことをひとつ決めて、予定から外す。","motion":["prepare"],"life_theme":["休息"],"status":"draft"},
    {"id":"ac-2-06","palace":2,"text":"財布のレシートを整理して、残高をさっと確認。","motion":["prepare"],"life_theme":["お金"],"status":"draft"},
    {"id":"ac-2-07","palace":2,"text":"いつもの飲み物を、座ってゆっくり味わおう。","motion":["prepare"],"life_theme":["休息"],"status":"draft"},
    {"id":"ac-2-08","palace":2,"text":"今夜休む時間を決めて、アラームを先にセット。","motion":["prepare"],"life_theme":["身体"],"status":"draft"},
    {"id":"ac-3-01","palace":3,"text":"止まっていた資料を開いて、最初の一行だけ書く。","motion":["start"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-3-02","palace":3,"text":"気になる講座の日程を調べて、予定表に入れておこう。","motion":["start"],"life_theme":["学び"],"status":"draft"},
    {"id":"ac-3-03","palace":3,"text":"やってみたかった運動を、動画1本分だけ始める。","motion":["start"],"life_theme":["身体"],"status":"draft"},
    {"id":"ac-3-04","palace":3,"text":"迷っていた予約は、空き状況を見るところまで。","motion":["start"],"life_theme":["決断"],"status":"draft"},
    {"id":"ac-3-05","palace":3,"text":"発信したいテーマをひとつ選び、見出しだけ作ろう。","motion":["start"],"life_theme":["発信"],"status":"draft"},
    {"id":"ac-3-06","palace":3,"text":"新しく使いたいものを、今日からひとつ下ろす。","motion":["start"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-3-07","palace":3,"text":"気になる相手に、まずは短い挨拶を送ってみて。","motion":["start"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-3-08","palace":3,"text":"500円だけ、未来の楽しみ用に分けておく。","motion":["start"],"life_theme":["お金"],"status":"draft"},
    {"id":"ac-4-01","palace":4,"text":"ふと思い浮かんだ人に「元気？」と送ってみて。","motion":["connect"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-4-02","palace":4,"text":"気になる誘いが来たら、予定だけ先に確認しよう。","motion":["connect"],"life_theme":["決断"],"status":"draft"},
    {"id":"ac-4-03","palace":4,"text":"仕事で迷っていることを、詳しい人にひとつ聞く。","motion":["connect"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-4-04","palace":4,"text":"いつも会う人に、自分から笑顔で挨拶を。","motion":["connect"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-4-05","palace":4,"text":"会いたい人とのランチ候補日を、2つだけ出しておく。","motion":["connect"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-4-06","palace":4,"text":"うれしかった投稿に、ひと言コメントを残そう。","motion":["connect"],"life_theme":["発信"],"status":"draft"},
    {"id":"ac-4-07","palace":4,"text":"声が聞きたい人に、5分だけ電話できるか聞いてみる。","motion":["connect"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-4-08","palace":4,"text":"役立ちそうな記事を、必要としている人にシェア。","motion":["connect"],"life_theme":["学び"],"status":"draft"},
    {"id":"ac-5-01","palace":5,"text":"人に合わせて入れた予定を、ひとつ見直してみて。","motion":["center"],"life_theme":["決断"],"status":"draft"},
    {"id":"ac-5-02","palace":5,"text":"ランチは「本当に食べたいもの」で選ぼう。","motion":["center"],"life_theme":["身体"],"status":"draft"},
    {"id":"ac-5-03","palace":5,"text":"頼まれごとに返事をする前に、予定を一度確認。","motion":["center"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-5-04","palace":5,"text":"見なくてもいい通知を、今日だけオフにしておく。","motion":["center"],"life_theme":["休息"],"status":"draft"},
    {"id":"ac-5-05","palace":5,"text":"今日いちばん大事なことに、丸をひとつつける。","motion":["center"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-5-06","palace":5,"text":"着心地のいい服に替えて、落ち着く方を選ぶ。","motion":["center"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-5-07","palace":5,"text":"「私はどうしたい？」の答えを、一行だけ書こう。","motion":["center"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-5-08","palace":5,"text":"誰にも合わせない10分を、予定の中に確保。","motion":["center"],"life_theme":["休息"],"status":"draft"},
    {"id":"ac-6-01","palace":6,"text":"いつもより上質な飲み物を、ひとつ選んでみて。","motion":["elevate"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-6-02","palace":6,"text":"大切なメモは、気に入っているペンで書こう。","motion":["elevate"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-6-03","palace":6,"text":"気になっていたお店に入り、商品をひとつ見てみる。","motion":["elevate"],"life_theme":["お金"],"status":"draft"},
    {"id":"ac-6-04","palace":6,"text":"座る場所を選べるなら、景色のいい席へ。","motion":["elevate"],"life_theme":["休息"],"status":"draft"},
    {"id":"ac-6-05","palace":6,"text":"尊敬する人の言葉をひとつ調べて、ノートに残す。","motion":["elevate"],"life_theme":["学び"],"status":"draft"},
    {"id":"ac-6-06","palace":6,"text":"アクセサリーをひとつ足して、鏡を見てから出かける。","motion":["elevate"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-6-07","palace":6,"text":"いつもの食事を、好きなお皿にきれいに盛りつけよう。","motion":["elevate"],"life_theme":["身体"],"status":"draft"},
    {"id":"ac-6-08","palace":6,"text":"送る文章を一度読み返して、言葉をひとつ磨く。","motion":["elevate"],"life_theme":["発信"],"status":"draft"},
    {"id":"ac-7-01","palace":7,"text":"褒められたら、謙遜せず「ありがとう」で受け取る。","motion":["receive"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-7-02","palace":7,"text":"もらったままの贈り物を、今日から使い始めよう。","motion":["receive"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-7-03","palace":7,"text":"誰かが手伝ってくれたら、遠慮せずお願いする。","motion":["receive"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-7-04","palace":7,"text":"うれしかったことを3つ、スマホのメモに残して。","motion":["receive"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-7-05","palace":7,"text":"いただきもののお菓子を、飲み物と一緒に味わう。","motion":["receive"],"life_theme":["休息"],"status":"draft"},
    {"id":"ac-7-06","palace":7,"text":"心に残ったメッセージは、スクリーンショットで保存。","motion":["receive"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-7-07","palace":7,"text":"今日できたことをひとつ数えて、声に出して認めよう。","motion":["receive"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-7-08","palace":7,"text":"帰りに小さなご褒美をひとつ選ぶ。予算は先に決めて。","motion":["receive"],"life_theme":["お金"],"status":"draft"},
    {"id":"ac-8-01","palace":8,"text":"もう使わないものをひとつ選び、手放す箱へ。","motion":["release"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-8-02","palace":8,"text":"読んでいないメルマガを、ひとつだけ解除しよう。","motion":["release"],"life_theme":["発信"],"status":"draft"},
    {"id":"ac-8-03","palace":8,"text":"古い下書きを見直して、不要ならゴミ箱に移す。","motion":["release"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-8-04","palace":8,"text":"気が進まない予定を、別日に動かせないか確認。","motion":["release"],"life_theme":["決断"],"status":"draft"},
    {"id":"ac-8-05","palace":8,"text":"開きっぱなしの画面を閉じて、今使うものだけ残す。","motion":["release"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-8-06","palace":8,"text":"使っていないアプリをひとつ、ホーム画面から外す。","motion":["release"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-8-07","palace":8,"text":"くたびれたタオルを一枚替えて、気分も切り替えよう。","motion":["release"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-8-08","palace":8,"text":"終わりにしたい習慣をひとつ書いて、線を引く。","motion":["release"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-9-01","palace":9,"text":"作りかけのものを、信頼できる誰かに見せてみて。","motion":["express"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-9-02","palace":9,"text":"会議では、自分の意見をひと言だけ先に伝えよう。","motion":["express"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-9-03","palace":9,"text":"好きな色の服を選んで、隠さない方へ。","motion":["express"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-9-04","palace":9,"text":"今日の一枚を撮って、送りたい人に送る。","motion":["express"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-9-05","palace":9,"text":"プロフィールの一文を、今の自分に合わせて直す。","motion":["express"],"life_theme":["発信"],"status":"draft"},
    {"id":"ac-9-06","palace":9,"text":"書きかけの文章から、好きな一節だけ公開してみて。","motion":["express"],"life_theme":["発信"],"status":"draft"},
    {"id":"ac-9-07","palace":9,"text":"「私はこれが好き」と、会話の中で一度言ってみよう。","motion":["express"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-9-08","palace":9,"text":"お気に入りのものを、目に入る場所に飾っておく。","motion":["express"],"life_theme":["暮らし"],"status":"draft"}
  ];
});
