/*
 * 運命リズム診断 — 今日の一歩プール（各宮8本）
 * 選び方: 日の宮×THEMEのmotion一致→日付で回転
 * 2026-08-25 せいこさんの声基準（day_base 27本）に合わせてCodex再生成・クレア検品済み。
 * 2026-09-11 72本すべて、せいこさん執筆版に差し替え。「\n」＝せいこさん指定の改行位置（句点なし）。
 * status:'draft'＝せいこさんの週次チェック前。承認されたら status を外す。
 */
'use strict';
(function (root, factory) {
  if (typeof module === 'object' && module.exports) { module.exports = factory(); }
  else { root.UR_ACTIONS = factory(); }
})(typeof self !== 'undefined' ? self : this, function () {
  return [
    {"id":"ac-1-01","palace":1,"text":"気になっていること\nぜんぶノートに書き出そう","motion":["reflect"],"life_theme":["決断"],"status":"draft"},
    {"id":"ac-1-02","palace":1,"text":"来月やりたいこと\n現状無視で日付を入れてみて","motion":["reflect"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-1-03","palace":1,"text":"保存したままの記事、ない？\nひとつ選んで朝のうちに読もう","motion":["reflect"],"life_theme":["学び"],"status":"draft"},
    {"id":"ac-1-04","palace":1,"text":"「私、ほんとうは何がしたい？」\n3分だけノートに書き出して","motion":["reflect"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-1-05","palace":1,"text":"試したいアイデア\n仮でいいから言葉にしてみよう","motion":["reflect"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-1-06","palace":1,"text":"ふと浮かんだ言葉\nその場で音声メモに残して","motion":["reflect"],"life_theme":["発信"],"status":"draft"},
    {"id":"ac-1-07","palace":1,"text":"楽しみな予定\n第一優先でカレンダーに入れよう","motion":["reflect"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-1-08","palace":1,"text":"「いつか」欲しいもの\n値段と手に入れる方法を調べてみて","motion":["reflect"],"life_theme":["お金"],"status":"draft"},
    {"id":"ac-2-01","palace":2,"text":"机の上、もう使わないもの\nひとつ手放してすっきりしよう","motion":["prepare"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-2-02","palace":2,"text":"ポーチやバッグ\n今日使わないものは置いていこう","motion":["prepare"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-2-03","palace":2,"text":"首、肩、ゆっくり回して\n深い呼吸を3回しよう","motion":["prepare"],"life_theme":["身体"],"status":"draft"},
    {"id":"ac-2-04","palace":2,"text":"後回しにしていたお返事\nいったん先に返しておこう","motion":["prepare"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-2-05","palace":2,"text":"今日じゃなくていいやというもの\n先にやってしまうとすっきりするね","motion":["prepare"],"life_theme":["休息"],"status":"draft"},
    {"id":"ac-2-06","palace":2,"text":"お財布はお金のおうち\nレシートは整理、お金は整えて","motion":["prepare"],"life_theme":["お金"],"status":"draft"},
    {"id":"ac-2-07","palace":2,"text":"いつもの飲み物も\n今日は座ってゆっくり味わって","motion":["prepare"],"life_theme":["休息"],"status":"draft"},
    {"id":"ac-2-08","palace":2,"text":"今夜休む時間を決めて\n先にアラームをセットしよう","motion":["prepare"],"life_theme":["身体"],"status":"draft"},
    {"id":"ac-3-01","palace":3,"text":"止まっていたこと\n最初の一歩だけ動かしてみよう","motion":["start"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-3-02","palace":3,"text":"気になっている講座や予定\n日程を調べてカレンダーへ","motion":["start"],"life_theme":["学び"],"status":"draft"},
    {"id":"ac-3-03","palace":3,"text":"やってみたかった運動\n今日はまず始めてみよう","motion":["start"],"life_theme":["身体"],"status":"draft"},
    {"id":"ac-3-04","palace":3,"text":"迷っていた予約\n空き状況見て予約もしよう","motion":["start"],"life_theme":["決断"],"status":"draft"},
    {"id":"ac-3-05","palace":3,"text":"発信したいこと\n完璧にしようとせずとりあえず出してみて","motion":["start"],"life_theme":["発信"],"status":"draft"},
    {"id":"ac-3-06","palace":3,"text":"古いものひとつ\n新しくしてみましょう","motion":["start"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-3-07","palace":3,"text":"声が聞きたいなぁと思った人\n「少し話せる？」と連絡してみよう","motion":["start"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-3-08","palace":3,"text":"ノリノリな音楽\n気分転換にかけてみて♪","motion":["start"],"life_theme":["お金"],"status":"draft"},
    {"id":"ac-4-01","palace":4,"text":"ふと思い浮かんだ人に\n「元気？」と送ってみて","motion":["connect"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-4-02","palace":4,"text":"気になるお誘いが来たら\n即「YES!」予定確認はそのあと","motion":["connect"],"life_theme":["決断"],"status":"draft"},
    {"id":"ac-4-03","palace":4,"text":"迷っていること\n詳しい人にちょっと聞いてみて","motion":["connect"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-4-04","palace":4,"text":"いつも会う人にも\n今日は自分から笑顔で挨拶を","motion":["connect"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-4-05","palace":4,"text":"会いたい人、思い浮かんだ人\nランチに誘ってみない？","motion":["connect"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-4-06","palace":4,"text":"心が動いた投稿に\nひと言コメントを残してみて","motion":["connect"],"life_theme":["発信"],"status":"draft"},
    {"id":"ac-4-07","palace":4,"text":"行ってみたい海外のあの場所\n具体的に調べてみて","motion":["connect"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-4-08","palace":4,"text":"役立ちそうな情報\n思い浮かんだ人にシェアしよう","motion":["connect"],"life_theme":["学び"],"status":"draft"},
    {"id":"ac-5-01","palace":5,"text":"人に合わせて入れた予定\n本当に必要か見直してみよう","motion":["center"],"life_theme":["決断"],"status":"draft"},
    {"id":"ac-5-02","palace":5,"text":"今日のランチは\n「本当に食べたいもの」を選んで","motion":["center"],"life_theme":["身体"],"status":"draft"},
    {"id":"ac-5-03","palace":5,"text":"頼まれごとに返事をする前に\n自分の「やりたい」を優先して","motion":["center"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-5-04","palace":5,"text":"見なくていい通知\n今日は思い切ってオフにして","motion":["center"],"life_theme":["休息"],"status":"draft"},
    {"id":"ac-5-05","palace":5,"text":"今日いちばん大切なこと\nひとつ赤線つけてみよう","motion":["center"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-5-06","palace":5,"text":"今日の下着や洋服\n化繊よりコットン、オーガニックなものを","motion":["center"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-5-07","palace":5,"text":"「私はどうしたい？」\n答えをひとつ書いてみよう","motion":["center"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-5-08","palace":5,"text":"誰にも合わせない10分\n自分のために先に確保して","motion":["center"],"life_theme":["休息"],"status":"draft"},
    {"id":"ac-6-01","palace":6,"text":"いつもの飲み物も\n今日は少し上質なものを選んで","motion":["elevate"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-6-02","palace":6,"text":"大切なことを書くなら\nお気に入りのペンを使ってみて","motion":["elevate"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-6-03","palace":6,"text":"気になっていたお店\n今日は一度入ってみよう","motion":["elevate"],"life_theme":["お金"],"status":"draft"},
    {"id":"ac-6-04","palace":6,"text":"座る場所を選べるなら\n気分の上がる席を選んで","motion":["elevate"],"life_theme":["休息"],"status":"draft"},
    {"id":"ac-6-05","palace":6,"text":"尊敬する人の言葉\nひとつ見つけてノートに残そう","motion":["elevate"],"life_theme":["学び"],"status":"draft"},
    {"id":"ac-6-06","palace":6,"text":"アクセサリーをひとつ足して\nいつもより少し華やかに","motion":["elevate"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-6-07","palace":6,"text":"いつもの食事も\nお気に入りの器に盛りつけて","motion":["elevate"],"life_theme":["身体"],"status":"draft"},
    {"id":"ac-6-08","palace":6,"text":"それ、あなたを素敵に見せる？\n妥協ではなくベストで選んで","motion":["elevate"],"life_theme":["発信"],"status":"draft"},
    {"id":"ac-7-01","palace":7,"text":"褒められたら\n「ありがとう」でそのまま受け取って","motion":["receive"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-7-02","palace":7,"text":"しまったままのお気に入り\n今日から使い始めよう","motion":["receive"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-7-03","palace":7,"text":"手伝ってもらえることは\n今日は素直にお願いしてみて","motion":["receive"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-7-04","palace":7,"text":"今日うれしかったこと\n3つ以上思い出してノートに書こう","motion":["receive"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-7-05","palace":7,"text":"好きな食べ物\n好きな飲み物と一緒に楽しんで","motion":["receive"],"life_theme":["休息"],"status":"draft"},
    {"id":"ac-7-06","palace":7,"text":"心に残ったメッセージ\nあとで見返せるように残しておこう","motion":["receive"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-7-07","palace":7,"text":"今日できたこと\nひとつ声に出して認めよう","motion":["receive"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-7-08","palace":7,"text":"帰り道に\n小さなご褒美をひとつ選んで","motion":["receive"],"life_theme":["お金"],"status":"draft"},
    {"id":"ac-8-01","palace":8,"text":"使ってない不要なもの\nひとつ選んで手放そう","motion":["release"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-8-02","palace":8,"text":"読まなくなったメルマガ\nひとつ解除してすっきり","motion":["release"],"life_theme":["発信"],"status":"draft"},
    {"id":"ac-8-03","palace":8,"text":"古い下書きを見直して\nいらないものは削除しよう","motion":["release"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-8-04","palace":8,"text":"気が進まない予定\n動かせないか一度確認してみて","motion":["release"],"life_theme":["決断"],"status":"draft"},
    {"id":"ac-8-05","palace":8,"text":"開きっぱなしの画面を閉じて\n今必要なものだけ残そう","motion":["release"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-8-06","palace":8,"text":"使っていないアプリ\nひとつホーム画面から外して","motion":["release"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-8-07","palace":8,"text":"くたびれたものを替えて\n気分も新しくしよう","motion":["release"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"ac-8-08","palace":8,"text":"終わりにしたい習慣\n今日から手放し、線を引こう","motion":["release"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-9-01","palace":9,"text":"役に立たないもの、美しくないものは\n日常には置かないで","motion":["express"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-9-02","palace":9,"text":"気になっていたこと\nとことん調べてシェアしてみよう","motion":["express"],"life_theme":["仕事"],"status":"draft"},
    {"id":"ac-9-03","palace":9,"text":"好きな色を身につけて\n隠さない自分で出かけてみよう","motion":["express"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-9-04","palace":9,"text":"いっちばん素敵な自分\n笑顔で自撮りしてみよう","motion":["express"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"ac-9-05","palace":9,"text":"プロフィールの一文\n今の自分に合わせて更新しよう","motion":["express"],"life_theme":["発信"],"status":"draft"},
    {"id":"ac-9-06","palace":9,"text":"世界は広い人生は一度きり\n自分軸で選んでみて","motion":["express"],"life_theme":["発信"],"status":"draft"},
    {"id":"ac-9-07","palace":9,"text":"「私はこれが好き」\n今日は一度ちゃんと言ってみよう","motion":["express"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"ac-9-08","palace":9,"text":"お気に入りのもの\nいちばん目に入る場所に飾ろう","motion":["express"],"life_theme":["暮らし"],"status":"draft"}
  ];
});
