/*
 * 運命リズム診断 — 今日のテーマ候補プール（各宮8本）
 * 選び方: 日の宮が主軸→月・年・本質との相性スコア（js/select.js）
 * 2026-08-25 Codex一括生成・クレア検品済み。status:'draft'＝せいこさんの週次チェック前。
 * チェックで承認されたら status を外す。文章の修正はこのファイルを直接編集してよい。
 */
'use strict';
(function (root, factory) {
  if (typeof module === 'object' && module.exports) { module.exports = factory(); }
  else { root.UR_THEMES = factory(); }
})(typeof self !== 'undefined' ? self : this, function () {
  return [
    {"id":"th-1-01","palace":1,"text":"未来を思い描く","motion":["reflect"],"life_theme":[],"status":"draft"},
    {"id":"th-1-02","palace":1,"text":"気になるをメモ","motion":["reflect","prepare"],"life_theme":["学び"],"status":"draft"},
    {"id":"th-1-03","palace":1,"text":"新しい予感を選ぶ","motion":["reflect"],"life_theme":["決断"],"status":"draft"},
    {"id":"th-1-04","palace":1,"text":"心の声を拾う","motion":["reflect","center"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"th-1-05","palace":1,"text":"やりたいこと探し","motion":["reflect"],"life_theme":["仕事"],"status":"draft"},
    {"id":"th-1-06","palace":1,"text":"夢の続きを考える","motion":["reflect"],"life_theme":[],"status":"draft"},
    {"id":"th-1-07","palace":1,"text":"ひらめきを残す","motion":["reflect","prepare"],"life_theme":["発信"],"status":"draft"},
    {"id":"th-1-08","palace":1,"text":"これからを決める","motion":["reflect","center"],"life_theme":["決断"],"status":"draft"},
    {"id":"th-2-01","palace":2,"text":"足元から整える","motion":["prepare"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"th-2-02","palace":2,"text":"小さな用事を片づける","motion":["prepare"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"th-2-03","palace":2,"text":"自分をいたわる","motion":["prepare"],"life_theme":["身体"],"status":"draft"},
    {"id":"th-2-04","palace":2,"text":"明日の準備を楽しむ","motion":["prepare"],"life_theme":["仕事"],"status":"draft"},
    {"id":"th-2-05","palace":2,"text":"心地よさを選ぶ","motion":["prepare","center"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"th-2-06","palace":2,"text":"机まわりを整える","motion":["prepare"],"life_theme":["仕事"],"status":"draft"},
    {"id":"th-2-07","palace":2,"text":"早めにひと休み","motion":["prepare"],"life_theme":["休息"],"status":"draft"},
    {"id":"th-2-08","palace":2,"text":"大切なものを育てる","motion":["prepare"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"th-3-01","palace":3,"text":"まずやってみる","motion":["start"],"life_theme":[],"status":"draft"},
    {"id":"th-3-02","palace":3,"text":"小さく始める","motion":["start"],"life_theme":["仕事"],"status":"draft"},
    {"id":"th-3-03","palace":3,"text":"好奇心のまま動く","motion":["start"],"life_theme":["学び"],"status":"draft"},
    {"id":"th-3-04","palace":3,"text":"最初の一歩を楽しむ","motion":["start"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"th-3-05","palace":3,"text":"やりたいを形にする","motion":["start","express"],"life_theme":["発信"],"status":"draft"},
    {"id":"th-3-06","palace":3,"text":"今すぐ試してみる","motion":["start"],"life_theme":["仕事"],"status":"draft"},
    {"id":"th-3-07","palace":3,"text":"新しい私を始める","motion":["start"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"th-3-08","palace":3,"text":"迷う前に動く","motion":["start","center"],"life_theme":["決断"],"status":"draft"},
    {"id":"th-4-01","palace":4,"text":"会いたい人に連絡","motion":["connect"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"th-4-02","palace":4,"text":"誘いに乗ってみる","motion":["connect","start"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"th-4-03","palace":4,"text":"人との時間を楽しむ","motion":["connect","receive"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"th-4-04","palace":4,"text":"うれしい予定を入れる","motion":["connect"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"th-4-05","palace":4,"text":"言葉を交わす","motion":["connect","express"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"th-4-06","palace":4,"text":"会いに行く","motion":["connect","start"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"th-4-07","palace":4,"text":"ご縁を深める","motion":["connect"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"th-4-08","palace":4,"text":"一緒にやってみる","motion":["connect","start"],"life_theme":["仕事"],"status":"draft"},
    {"id":"th-5-01","palace":5,"text":"本音で選ぶ","motion":["center"],"life_theme":["決断"],"status":"draft"},
    {"id":"th-5-02","palace":5,"text":"私らしさに戻る","motion":["center"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"th-5-03","palace":5,"text":"心地よい方へ","motion":["center"],"life_theme":["決断"],"status":"draft"},
    {"id":"th-5-04","palace":5,"text":"私の気持ちを優先","motion":["center"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"th-5-05","palace":5,"text":"無理のない方を選ぶ","motion":["center"],"life_theme":["身体"],"status":"draft"},
    {"id":"th-5-06","palace":5,"text":"好きに正直になる","motion":["center"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"th-5-07","palace":5,"text":"自分のペースを守る","motion":["center"],"life_theme":["休息"],"status":"draft"},
    {"id":"th-5-08","palace":5,"text":"納得できる答えを選ぶ","motion":["center","reflect"],"life_theme":["決断"],"status":"draft"},
    {"id":"th-6-01","palace":6,"text":"上質をひとつ選ぶ","motion":["elevate"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"th-6-02","palace":6,"text":"憧れの場所へ行く","motion":["elevate","start"],"life_theme":[],"status":"draft"},
    {"id":"th-6-03","palace":6,"text":"いつもより素敵に","motion":["elevate","express"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"th-6-04","palace":6,"text":"理想に似合う選択","motion":["elevate"],"life_theme":["決断"],"status":"draft"},
    {"id":"th-6-05","palace":6,"text":"背筋を伸ばして進む","motion":["elevate"],"life_theme":["身体"],"status":"draft"},
    {"id":"th-6-06","palace":6,"text":"ワンランク上を選ぶ","motion":["elevate"],"life_theme":["お金"],"status":"draft"},
    {"id":"th-6-07","palace":6,"text":"未来の私を先取り","motion":["elevate"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"th-6-08","palace":6,"text":"憧れを日常にする","motion":["elevate"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"th-7-01","palace":7,"text":"喜びを受け取る","motion":["receive"],"life_theme":[],"status":"draft"},
    {"id":"th-7-02","palace":7,"text":"褒め言葉にありがとう","motion":["receive"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"th-7-03","palace":7,"text":"ご褒美を楽しむ","motion":["receive"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"th-7-04","palace":7,"text":"うれしさを味わう","motion":["receive"],"life_theme":[],"status":"draft"},
    {"id":"th-7-05","palace":7,"text":"好意を素直に受け取る","motion":["receive"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"th-7-06","palace":7,"text":"豊かさに気づく","motion":["receive"],"life_theme":["お金"],"status":"draft"},
    {"id":"th-7-07","palace":7,"text":"愛されていると知る","motion":["receive"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"th-7-08","palace":7,"text":"幸せを受け取る♡","motion":["receive"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"th-8-01","palace":8,"text":"もう終わりにする","motion":["release"],"life_theme":["決断"],"status":"draft"},
    {"id":"th-8-02","palace":8,"text":"気持ちを切り替える","motion":["release","center"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"th-8-03","palace":8,"text":"手放して軽やかに","motion":["release"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"th-8-04","palace":8,"text":"予定をひとつ減らす","motion":["release"],"life_theme":["休息"],"status":"draft"},
    {"id":"th-8-05","palace":8,"text":"いらないものを手放す","motion":["release"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"th-8-06","palace":8,"text":"過去より今を選ぶ","motion":["release","center"],"life_theme":["決断"],"status":"draft"},
    {"id":"th-8-07","palace":8,"text":"無理な約束をやめる","motion":["release"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"th-8-08","palace":8,"text":"新しい余白をつくる","motion":["release","prepare"],"life_theme":["暮らし"],"status":"draft"},
    {"id":"th-9-01","palace":9,"text":"私らしさを見せる","motion":["express"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"th-9-02","palace":9,"text":"思いを言葉にする","motion":["express"],"life_theme":["発信"],"status":"draft"},
    {"id":"th-9-03","palace":9,"text":"できたものを届ける","motion":["express","connect"],"life_theme":["仕事"],"status":"draft"},
    {"id":"th-9-04","palace":9,"text":"好きなものを語る","motion":["express"],"life_theme":["発信"],"status":"draft"},
    {"id":"th-9-05","palace":9,"text":"魅力を隠さない","motion":["express"],"life_theme":["自己信頼"],"status":"draft"},
    {"id":"th-9-06","palace":9,"text":"誰かに見せてみる","motion":["express","connect"],"life_theme":["発信"],"status":"draft"},
    {"id":"th-9-07","palace":9,"text":"自分の考えを伝える","motion":["express"],"life_theme":["人間関係"],"status":"draft"},
    {"id":"th-9-08","palace":9,"text":"今日の私を表現する","motion":["express"],"life_theme":["発信"],"status":"draft"}
  ];
});
